-- Execute no SQL Editor do Supabase.
-- O bucket público é apenas para leitura das imagens. Envie os arquivos pelo
-- Storage do Supabase e registre suas URLs públicas em icones_missoes.icone.
INSERT INTO storage.buckets (id, name, public)
VALUES ('missoes-icons', 'missoes-icons', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- A tabela missoes atual usa uma única turmaId. Mantemos a coluna por
-- compatibilidade e criamos uma relação N:N para as missões novas.
ALTER TABLE public.missoes
  ADD COLUMN IF NOT EXISTS dificuldade text;

UPDATE public.missoes
SET dificuldade = CASE
      WHEN COALESCE(xp, 0) <= 100 THEN 'facil'
      WHEN COALESCE(xp, 0) <= 300 THEN 'media'
      ELSE 'dificil'
    END,
    xp = CASE
      WHEN COALESCE(xp, 0) <= 100 THEN 100
      WHEN COALESCE(xp, 0) <= 300 THEN 300
      ELSE 500
    END;

ALTER TABLE public.missoes
  ALTER COLUMN dificuldade SET DEFAULT 'media',
  ALTER COLUMN dificuldade SET NOT NULL,
  ALTER COLUMN xp SET DEFAULT 300,
  ALTER COLUMN xp SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'missoes_dificuldade_xp_check'
      AND conrelid = 'public.missoes'::regclass
  ) THEN
    ALTER TABLE public.missoes
      ADD CONSTRAINT missoes_dificuldade_xp_check
      CHECK (
        (dificuldade = 'facil' AND xp = 100) OR
        (dificuldade = 'media' AND xp = 300) OR
        (dificuldade = 'dificil' AND xp = 500)
      );
  END IF;
END $$;

-- Catálogo das imagens. icone recebe a URL pública do objeto no Storage.
CREATE TABLE IF NOT EXISTS public.icones_missoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  icone text NOT NULL UNIQUE,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now()
);

-- Relação de uma missão com uma ou mais turmas; o par não pode se repetir.
CREATE TABLE IF NOT EXISTS public.missoes_turmas (
  missao_id bigint NOT NULL REFERENCES public.missoes(id) ON DELETE CASCADE,
  turma_id bigint NOT NULL REFERENCES public.turmas(id) ON DELETE CASCADE,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT missoes_turmas_pkey PRIMARY KEY (missao_id, turma_id)
);

INSERT INTO public.missoes_turmas (missao_id, turma_id)
SELECT id, "turmaId"
FROM public.missoes
WHERE "turmaId" IS NOT NULL
ON CONFLICT (missao_id, turma_id) DO NOTHING;

-- Histórico por aluno. xp_aluno e xp_pet guardam exatamente o valor concedido
-- para que uma edição ou exclusão reverta o valor correto.
CREATE TABLE IF NOT EXISTS public.alunos_missoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id bigint NOT NULL REFERENCES public.alunos(id) ON DELETE CASCADE,
  missao_id bigint NOT NULL REFERENCES public.missoes(id) ON DELETE CASCADE,
  turma_id bigint REFERENCES public.turmas(id) ON DELETE SET NULL,
  pet_id bigint REFERENCES public.pets(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pendente'
    CHECK (status IN ('pendente', 'entregue', 'aprovado')),
  xp_aluno bigint NOT NULL DEFAULT 0 CHECK (xp_aluno >= 0),
  xp_pet bigint NOT NULL DEFAULT 0 CHECK (xp_pet >= 0),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alunos_missoes_aluno_missao_unique UNIQUE (aluno_id, missao_id)
);

CREATE INDEX IF NOT EXISTS alunos_missoes_missao_idx
  ON public.alunos_missoes (missao_id);
CREATE INDEX IF NOT EXISTS alunos_missoes_turma_idx
  ON public.alunos_missoes (turma_id);

-- Só uma conclusão aprovada concede XP. A turma vem do aluno e precisa estar
-- vinculada à missão; o PET é o único que tem pets.turma_id igual à turma.
CREATE OR REPLACE FUNCTION public.preparar_aluno_missao()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_turma_id bigint;
  v_pet_id bigint;
  v_missao_xp bigint;
  v_missao_ativa boolean;
BEGIN
  IF NEW.status NOT IN ('pendente', 'entregue', 'aprovado') THEN
    RAISE EXCEPTION 'Status de missão inválido: %', NEW.status;
  END IF;

  IF TG_OP = 'UPDATE' AND OLD.status = 'aprovado' AND NEW.status <> 'aprovado' THEN
    NEW.xp_aluno := 0;
    NEW.xp_pet := 0;
    NEW.turma_id := OLD.turma_id;
    NEW.pet_id := OLD.pet_id;
    NEW.atualizado_em := now();
    RETURN NEW;
  END IF;

  IF NEW.status = 'aprovado' THEN
    IF TG_OP = 'UPDATE' AND OLD.status = 'aprovado' THEN
      NEW.turma_id := OLD.turma_id;
      NEW.pet_id := OLD.pet_id;
    ELSE
      SELECT m.xp, m.ativa
        INTO v_missao_xp, v_missao_ativa
      FROM public.missoes AS m
      WHERE m.id = NEW.missao_id;

      IF NOT FOUND THEN
        RAISE EXCEPTION 'Missão não encontrada.';
      END IF;
      IF NOT v_missao_ativa THEN
        RAISE EXCEPTION 'Esta missão está desativada e não pode conceder XP.';
      END IF;

      SELECT a."turmaId"
        INTO v_turma_id
      FROM public.alunos AS a
      WHERE a.id = NEW.aluno_id;

      IF v_turma_id IS NULL THEN
        RAISE EXCEPTION 'O aluno não está associado a uma turma.';
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM public.missoes_turmas AS mt
        WHERE mt.missao_id = NEW.missao_id AND mt.turma_id = v_turma_id
      ) THEN
        RAISE EXCEPTION 'A missão não está atribuída à turma do aluno.';
      END IF;

      SELECT p.id INTO v_pet_id
      FROM public.pets AS p
      WHERE p.turma_id = v_turma_id
      FOR UPDATE;

      IF v_pet_id IS NULL THEN
        RAISE EXCEPTION 'A turma do aluno não tem um PET vinculado.';
      END IF;

      NEW.turma_id := v_turma_id;
      NEW.pet_id := v_pet_id;
      NEW.xp_aluno := v_missao_xp;
      NEW.xp_pet := v_missao_xp;
    END IF;
  ELSE
    IF TG_OP = 'INSERT' THEN
      SELECT a."turmaId" INTO NEW.turma_id
      FROM public.alunos AS a
      WHERE a.id = NEW.aluno_id;
    ELSIF OLD.status <> 'aprovado' THEN
      SELECT a."turmaId" INTO NEW.turma_id
      FROM public.alunos AS a
      WHERE a.id = NEW.aluno_id;
    END IF;
    NEW.pet_id := NULL;
    NEW.xp_aluno := 0;
    NEW.xp_pet := 0;
  END IF;

  NEW.atualizado_em := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS alunos_missoes_preparar ON public.alunos_missoes;
CREATE TRIGGER alunos_missoes_preparar
BEFORE INSERT OR UPDATE ON public.alunos_missoes
FOR EACH ROW EXECUTE FUNCTION public.preparar_aluno_missao();

-- Ajusta os dois saldos exatamente pela diferença registrada no histórico.
CREATE OR REPLACE FUNCTION public.aplicar_xp_aluno_missao()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_aluno_delta bigint;
  v_pet_delta bigint;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_aluno_delta := NEW.xp_aluno;
    v_pet_delta := NEW.xp_pet;
    IF v_aluno_delta <> 0 THEN
      UPDATE public.alunos
      SET xp = GREATEST(COALESCE(xp, 0) + v_aluno_delta, 0)
      WHERE id = NEW.aluno_id;
    END IF;
    IF v_pet_delta <> 0 AND NEW.pet_id IS NOT NULL THEN
      UPDATE public.pets
      SET xp = GREATEST(COALESCE(xp, 0) + v_pet_delta, 0)
      WHERE id = NEW.pet_id;
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    IF OLD.xp_aluno <> 0 THEN
      UPDATE public.alunos
      SET xp = GREATEST(COALESCE(xp, 0) - OLD.xp_aluno, 0)
      WHERE id = OLD.aluno_id;
    END IF;
    IF OLD.xp_pet <> 0 AND OLD.pet_id IS NOT NULL THEN
      UPDATE public.pets
      SET xp = GREATEST(COALESCE(xp, 0) - OLD.xp_pet, 0)
      WHERE id = OLD.pet_id;
    END IF;
    RETURN OLD;
  END IF;

  v_aluno_delta := NEW.xp_aluno - OLD.xp_aluno;
  IF v_aluno_delta <> 0 THEN
    UPDATE public.alunos
    SET xp = GREATEST(COALESCE(xp, 0) + v_aluno_delta, 0)
    WHERE id = NEW.aluno_id;
  END IF;

  IF OLD.pet_id IS DISTINCT FROM NEW.pet_id THEN
    IF OLD.xp_pet <> 0 AND OLD.pet_id IS NOT NULL THEN
      UPDATE public.pets
      SET xp = GREATEST(COALESCE(xp, 0) - OLD.xp_pet, 0)
      WHERE id = OLD.pet_id;
    END IF;
    IF NEW.xp_pet <> 0 AND NEW.pet_id IS NOT NULL THEN
      UPDATE public.pets
      SET xp = GREATEST(COALESCE(xp, 0) + NEW.xp_pet, 0)
      WHERE id = NEW.pet_id;
    END IF;
  ELSE
    v_pet_delta := NEW.xp_pet - OLD.xp_pet;
    IF v_pet_delta <> 0 AND NEW.pet_id IS NOT NULL THEN
      UPDATE public.pets
      SET xp = GREATEST(COALESCE(xp, 0) + v_pet_delta, 0)
      WHERE id = NEW.pet_id;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS alunos_missoes_aplicar_xp ON public.alunos_missoes;
CREATE TRIGGER alunos_missoes_aplicar_xp
AFTER INSERT OR UPDATE OR DELETE ON public.alunos_missoes
FOR EACH ROW EXECUTE FUNCTION public.aplicar_xp_aluno_missao();

-- Ao mudar dificuldade/XP, atualiza os valores já concedidos. O trigger acima
-- aplica a diferença ao saldo do aluno e do PET; missões pausadas não são zeradas.
CREATE OR REPLACE FUNCTION public.sincronizar_xp_missao_editada()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NEW.xp IS DISTINCT FROM OLD.xp THEN
    UPDATE public.alunos_missoes
    SET xp_aluno = NEW.xp,
        xp_pet = NEW.xp
    WHERE missao_id = NEW.id
      AND status = 'aprovado'
      AND (xp_aluno IS DISTINCT FROM NEW.xp OR xp_pet IS DISTINCT FROM NEW.xp);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS missoes_sincronizar_xp ON public.missoes;
CREATE TRIGGER missoes_sincronizar_xp
AFTER UPDATE OF xp ON public.missoes
FOR EACH ROW EXECUTE FUNCTION public.sincronizar_xp_missao_editada();

-- Salva a missão e substitui suas turmas dentro de uma única transação.
CREATE OR REPLACE FUNCTION public.salvar_missao_com_turmas(
  p_missao_id bigint,
  p_professor_id bigint,
  p_nome text,
  p_descricao text,
  p_xp bigint,
  p_dificuldade text,
  p_icone text,
  p_ativa boolean,
  p_turmas_ids bigint[]
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_missao_id bigint;
  v_primeira_turma bigint;
BEGIN
  IF NOT (
    (p_dificuldade = 'facil' AND p_xp = 100) OR
    (p_dificuldade = 'media' AND p_xp = 300) OR
    (p_dificuldade = 'dificil' AND p_xp = 500)
  ) THEN
    RAISE EXCEPTION 'Dificuldade e XP não correspondem.';
  END IF;

  IF p_turmas_ids IS NULL OR cardinality(p_turmas_ids) = 0 THEN
    RAISE EXCEPTION 'Selecione ao menos uma turma.';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.icones_missoes
    WHERE icone = p_icone AND ativo = true
  ) THEN
    RAISE EXCEPTION 'Selecione um ícone ativo do catálogo.';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM unnest(p_turmas_ids) AS escolha(turma_id)
    LEFT JOIN public.turmas AS t
      ON t.id = escolha.turma_id AND t.professor_id = p_professor_id
    WHERE t.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Uma ou mais turmas não pertencem a este professor.';
  END IF;

  SELECT escolha.turma_id INTO v_primeira_turma
  FROM (SELECT DISTINCT unnest(p_turmas_ids) AS turma_id) AS escolha
  ORDER BY escolha.turma_id
  LIMIT 1;

  IF p_missao_id IS NULL THEN
    INSERT INTO public.missoes
      ("professorId", "turmaId", nome, descricao, xp, dificuldade, icone, ativa)
    VALUES
      (p_professor_id, v_primeira_turma, p_nome, p_descricao, p_xp, p_dificuldade, p_icone, p_ativa)
    RETURNING id INTO v_missao_id;
  ELSE
    UPDATE public.missoes
    SET "turmaId" = v_primeira_turma,
        nome = p_nome,
        descricao = p_descricao,
        xp = p_xp,
        dificuldade = p_dificuldade,
        icone = p_icone,
        ativa = p_ativa
    WHERE id = p_missao_id AND "professorId" = p_professor_id
    RETURNING id INTO v_missao_id;

    IF v_missao_id IS NULL THEN
      RAISE EXCEPTION 'Missão não encontrada ou não pertence a este professor.';
    END IF;

    DELETE FROM public.missoes_turmas WHERE missao_id = v_missao_id;
  END IF;

  INSERT INTO public.missoes_turmas (missao_id, turma_id)
  SELECT v_missao_id, DISTINCT_TURMAS.turma_id
  FROM (SELECT DISTINCT unnest(p_turmas_ids) AS turma_id) AS DISTINCT_TURMAS;

  RETURN v_missao_id;
END;
$$;

-- Atualiza apenas as turmas de uma missão a partir dos botões da tela.
CREATE OR REPLACE FUNCTION public.definir_turmas_missao(
  p_missao_id bigint,
  p_professor_id bigint,
  p_turmas_ids bigint[]
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_primeira_turma bigint;
BEGIN
  IF p_turmas_ids IS NULL OR cardinality(p_turmas_ids) = 0 THEN
    RAISE EXCEPTION 'Uma missão precisa estar atribuída a pelo menos uma turma.';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.missoes
    WHERE id = p_missao_id AND "professorId" = p_professor_id
  ) THEN
    RAISE EXCEPTION 'Missão não encontrada ou não pertence a este professor.';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM unnest(p_turmas_ids) AS escolha(turma_id)
    LEFT JOIN public.turmas AS t
      ON t.id = escolha.turma_id AND t.professor_id = p_professor_id
    WHERE t.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Uma ou mais turmas não pertencem a este professor.';
  END IF;

  SELECT turma_id INTO v_primeira_turma
  FROM (SELECT DISTINCT unnest(p_turmas_ids) AS turma_id) AS escolhas
  ORDER BY turma_id
  LIMIT 1;

  UPDATE public.missoes
  SET "turmaId" = v_primeira_turma
  WHERE id = p_missao_id AND "professorId" = p_professor_id;

  DELETE FROM public.missoes_turmas WHERE missao_id = p_missao_id;
  INSERT INTO public.missoes_turmas (missao_id, turma_id)
  SELECT p_missao_id, turma_id
  FROM (SELECT DISTINCT unnest(p_turmas_ids) AS turma_id) AS escolhas;
END;
$$;
